FIX centos7 ppa create failure
ceph repo update, related upstream link:
http://tracker.ceph.com/issues/16916

centos ceph-deploy rpm download failure workaround

Error info:

Package python-setuptools is obsoleted by python2-setuptools,
but obsoleting package does not provide for requirements
--> Finished Dependency Resolution
Error: Package: ceph-deploy-1.5.31-1.el7.noarch (centos-ceph-hammer)
           Requires: python-distribute
           Available: python-setuptools-0.9.8-4.el7.noarch (base)
               python-distribute = 0.9.8-4.el7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

JIRA: COMPASS-455

Change-Id: Ibebc8b25786b12308d5963e77b0f7959d700113a
Signed-off-by: QiLiang <liangqi1@huawei.com>